---

AWSTemplateFormatVersion: 2010-09-09

Description: "Test stack for the cloud-formation-rds-properties custom resource"

Parameters:

  RdsPropertiesStackname:
    Description: "The CloudFormation stack name containing the rds-properties resource"
    Type: "String"

  DbIdentifier:
    Description: "The DbInstanceIdentifier or DbClusterIdentifier of the RDS resource to connect to"
    Type: "String"

  DbIdentifierType:
    Description: "\"cluster\" or \"instance\" depending on the type of DbIdentifier"
    Type: "String"
    AllowedValues: ["cluster", "instance"]

Conditions:
  DbIdentifierIsInstance: !Equals [!Ref "DbIdentifierType", "instance"]
  DbIdentifierIsCluster: !Equals [!Ref "DbIdentifierType", "cluster"]

Resources:

  RdsProperties:
    Type: "AWS::CloudFormation::CustomResource"
    Version: "1.0"
    Properties:
      ServiceToken:
        Fn::ImportValue:
          !Sub "${RdsPropertiesStackname}-FunctionArn"
      DBInstanceIdentifier: !If
        - "DbIdentifierIsInstance"
        - !Ref "DbIdentifier"
        - !Ref "AWS::NoValue"
      DBClusterIdentifier: !If
        - "DbIdentifierIsCluster"
        - !Ref "DbIdentifier"
        - !Ref "AWS::NoValue"

Outputs:
  Arn:
    Description: "The ARN of the RDS Resource"
    Value: !GetAtt ["RdsProperties", "Arn"]

  ResourceId:
    Description: "The AWS Region-unique, immutable identifier for the RDS resource"
    Value: !GetAtt ["RdsProperties", "ResourceId"]

  DBName:
    Description: "The name of the database that was created with the RDS resource"
    Value: !GetAtt ["RdsProperties", "DBName"]

  EndpointAddress:
    Description: "The endpoint address of the RDS resource"
    Value: !GetAtt ["RdsProperties", "Endpoint.Address"]

  EndpointPort:
    Description: "The endpoint port of the RDS resource"
    Value: !GetAtt ["RdsProperties", "Endpoint.Port"]

  ReadEndpointAddress:
    Description: "The read endpoint address of the RDS resource"
    Value: !GetAtt ["RdsProperties", "ReadEndpoint.Address"]

  Engine:
    Description: "The engine of the RDS instance"
    Value: !GetAtt ["RdsProperties", "Engine"]

  EngineVersion:
    Description: "The engine version of the RDS instance"
    Value: !GetAtt ["RdsProperties", "EngineVersion"]

  IAMDatabaseAuthenticationEnabled:
    Description: "True if mapping of AWS Identity and Access Management (IAM) accounts to
database accounts is enabled, and otherwise false."
    Value: !GetAtt ["RdsProperties", "IAMDatabaseAuthenticationEnabled"]

  MasterUsername:
    Description: "The master username for the RDS instance"
    Value: !GetAtt ["RdsProperties", "MasterUsername"]

